# -*- coding: utf-8 -*-
"""find_categories.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CcVp4nIPpr3H9_hRm7jUvlFVPYYiEoNk
"""

import pandas as pd
import re

# ============================================================
# KEYWORD MAPPING FINAL (AKURAT SESUAI 25 DATA CONTOH)
# ============================================================

KEYWORD_MAP = {
    # =========================
    # PENDAPATAN
    # =========================

    # Pendapatan sewa kos bulanan
    "sewa kos": "Pendapatan sewa kos bulanan",
    "pendapatan sewa bulanan": "Pendapatan sewa kos bulanan",
    "sewa kamar": "Pendapatan sewa kos bulanan",
    "pendapatan sewa kamar": "Pendapatan sewa kos bulanan",

    # Layanan katering bulanan
    "katering": "Layanan katering bulanan",
    "catering": "Layanan katering bulanan",

    # Pendapatan laundry penghuni
    "laundry": "Pendapatan laundry penghuni",
    "cuci baju": "Pendapatan laundry penghuni",

    # Pendapatan sewa parkir motor
    "parkir motor": "Pendapatan sewa parkir motor",
    "sewa area parkir": "Pendapatan sewa parkir motor",
    "parkir": "Pendapatan sewa parkir motor",

    # Pendapatan sewa parkir mobil
    "parkir mobil": "Pendapatan sewa parkir mobil",

    # Pendapatan denda keterlambatan bayar
    "denda": "Pendapatan denda keterlambatan bayar",
    "denda bayar": "Pendapatan denda keterlambatan bayar",
    "denda terlambat": "Pendapatan denda keterlambatan bayar",

    # Pendapatan sewa ruang usaha warung
    "sewa ruang": "Pendapatan sewa ruang usaha warung",
    "sewa ruang usaha": "Pendapatan sewa ruang usaha warung",
    "sewa ruang kecil": "Pendapatan sewa ruang usaha warung",
    "ruang usaha": "Pendapatan sewa ruang usaha warung",

    # =========================
    # PENGELUARAN
    # =========================
    # Pemeliharaan
    "pemeliharaan": "Biaya pemeliharaan bangunan dan kamar kos",
    "perawatan": "Biaya pemeliharaan bangunan dan kamar kos",
    "maintenance": "Biaya pemeliharaan bangunan dan kamar kos",

    # Kunjungan dokter
    "dokter": "Biaya kunjungan dokter karena sakit",
    "kunjungan dokter": "Biaya kunjungan dokter karena sakit",

    # Pembelian obat
    "obat": "Pengeluaran / Pembelian obat",

    # Listrik
    "listrik": "Biaya listrik bulanan",

    # Air PAM
    "air": "Tagihan / biaya air PAM Bulanan",
    "pam": "Tagihan / biaya air PAM Bulanan",

    # Internet
    "wifi": "Biaya bulanan layanan internet & Wi-Fi",
    "wi-fi": "Biaya bulanan layanan internet & Wi-Fi",
    "internet": "Biaya bulanan layanan internet & Wi-Fi",

    # Renovasi kecil
    "renov": "Biaya renovasi kecil (cat, perbaikan pintu)",
    "renovasi": "Biaya renovasi kecil (cat, perbaikan pintu)",
    "cat": "Biaya renovasi kecil (cat, perbaikan pintu)",
    "ngecat": "Biaya renovasi kecil (cat, perbaikan pintu)",
    "perbaikan": "Biaya renovasi kecil (cat, perbaikan pintu)",
    "pintu": "Biaya renovasi kecil (cat, perbaikan pintu)",

    # Perabot
    "kasur": "Pembelian perabotan kamar kos (kasur, kipas, meja)",
    "kipas": "Pembelian perabotan kamar kos (kasur, kipas, meja)",
    "meja": "Pembelian perabotan kamar kos (kasur, kipas, meja)",
    "perabot": "Pembelian perabotan kamar kos (kasur, kipas, meja)",

    # Pajak PBB
    "pbb": "Pajak properti / PBB",
    "pajak": "Pajak properti / PBB",

    # =========================
    # TARIF BARU
    # =========================
    # Perubahan tarif sewa
    "penyesuaian sewa": "Penyesuaian / Perubahan Tarif atau Harga Sewa Kos",
    "perubahan tarif": "Penyesuaian / Perubahan Tarif atau Harga Sewa Kos",
    "perubahan harga sewa": "Penyesuaian / Perubahan Tarif atau Harga Sewa Kos",

    # Perubahan biaya pembangunan
    "pembangunan kamar": "Penyesuaian / Perubahan Biaya Pembangunan Kamar Kos",
    "biaya pembangunan": "Penyesuaian / Perubahan Biaya Pembangunan Kamar Kos",
    "pembangunan kos": "Penyesuaian / Perubahan Biaya Pembangunan Kamar Kos",
    "harga pembuatan": "Penyesuaian / Perubahan Biaya Pembangunan Kamar Kos",
    "kenaikan harga pembuatan": "Penyesuaian / Perubahan Biaya Pembangunan Kamar Kos",
    "perubahan harga kamar kos": "Penyesuaian / Perubahan Biaya Pembangunan Kamar Kos"
}

# ============================================================
# CLEANING
# ============================================================

def clean_text(text: str) -> str:
    if not isinstance(text, str):
        return ""
    text = text.lower()
    text = re.sub(r'[^a-z0-9\s]', ' ', text)
    return re.sub(r'\s+', ' ', text).strip()

# ============================================================
# DEBUG KEYWORD MATCH
# ============================================================

def keyword_fallback(desc: str):
    d = clean_text(desc)
    for key, akun in KEYWORD_MAP.items():
        if key in d:
            print(f"   🔎 Keyword match → '{key}' → {akun}")
            return akun
    print("   ⚠ Tidak ada keyword match")
    return None

# ============================================================
# NGRAM SIMILARITY (BACKUP)
# ============================================================

def ngram(tokens, n=3):
    return {tuple(tokens[i:i+n]) for i in range(len(tokens) - n + 1)}

def similarity_ngram(a: str, b: str, n=3) -> float:
    ta = clean_text(a).split()
    tb = clean_text(b).split()

    if len(ta) < n or len(tb) < n:
        sa, sb = set(ta), set(tb)
        if not sa or not sb:
            return 0.0
        return len(sa & sb) / len(sa | sb)

    na = ngram(ta, n)
    nb = ngram(tb, n)
    if not na or not nb:
        return 0.0

    return len(na & nb) / len(na | nb)

# ============================================================
# MAIN PROCESS WITH DEBUG
# ============================================================

def process_ngram_matching(
    master_file="master_akun.xlsx",
    master_sheet="Data",
    trx_file="transaksi.xlsx",
    trx_sheet="Data",
    output_file="transaksi_dengan_kategori.xlsx",
    output_sheet="Data"
):

    df_master = pd.read_excel(master_file, sheet_name=master_sheet)
    df_trx = pd.read_excel(trx_file, sheet_name=trx_sheet)

    df_master["Deskripsi"] = df_master["Deskripsi"].astype(str)

    akun_list = []
    kategori_list = []
    nominal_list = []
    tarif_baru_list = []

    master_desc = df_master["Deskripsi"].tolist()

    print("\n==================== MULAI DEBUG ====================\n")

    for idx, row in df_trx.iterrows():
        desc = str(row["Deskripsi Transaksi"])
        nominal_asli = row["Nominal"]

        print(f"\n[{idx+1}] 📝 Deskripsi: {desc}")

        # 1‰ Coba dengan keyword
        akun = keyword_fallback(desc)

        # 2‰ Jika gagal → pakai n-gram
        if akun is None:
            print("   ↔ Masuk mode n-gram similarity...")
            best_score = 0
            best_match = None

            for m in master_desc:
                score = similarity_ngram(desc, m)
                if score > best_score:
                    best_score = score
                    best_match = m

            akun = best_match
            print(f"     N-gram memilih: {akun} (score={best_score:.4f})")

        # Ambil kategori
        if akun is None:
            akun = "Tidak Ditemukan" # Default value if no match is found
            kategori = "Tidak Ditemukan" # Default value for Kategori
            print("   ❌ Akun dan Kategori tidak ditemukan setelah matching!")
        else:
            row_found = df_master.loc[df_master["Deskripsi"].str.lower() == akun.lower(), "Kategori"]

            if row_found.empty:
                kategori = "Tidak Ditemukan"
                print("   ❌ Kategori tidak ditemukan di master!")
            else:
                kategori = row_found.values[0]
                print(f"     Kategori: {kategori}")

        # Hitung nominal
        if kategori == "Pendapatan":
            nominal = abs(nominal_asli)
            tarif_baru = 0

        elif kategori == "Pengeluaran":
            nominal = -abs(nominal_asli)
            tarif_baru = 0

        elif kategori == "Tarif Baru":
            nominal = 0
            tarif_baru = abs(nominal_asli)

        else:
            nominal = nominal_asli
            tarif_baru = 0

        akun_list.append(akun)
        kategori_list.append(kategori)
        nominal_list.append(nominal)
        tarif_baru_list.append(tarif_baru)

    print("\n==================== DEBUG SELESAI ====================\n")

    # OUTPUT
    df_out = df_trx.copy()
    df_out["Akun"] = akun_list
    df_out["Kategori"] = kategori_list
    df_out["Nominal"] = nominal_list
    df_out["Tarif Baru"] = tarif_baru_list

    # Check if 'Nomor' column exists before trying to include it
    columns_to_select = [
        "Deskripsi Transaksi",
        "Akun",
        "Kategori",
        "Nominal",
        "Tarif Baru"
    ]
    if "Nomor" in df_out.columns:
        columns_to_select.insert(0, "Nomor")

    df_out = df_out[columns_to_select]

    df_out.to_excel(output_file, sheet_name=output_sheet, index=False)

    print("✔ File berhasil dibuat:", output_file)


if __name__ == "__main__":
    process_ngram_matching()