# -*- coding: utf-8 -*-
"""find_categories.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CcVp4nIPpr3H9_hRm7jUvlFVPYYiEoNk
"""

import pandas as pd
import re

# ==========================
# Toggle debug
# ==========================
DEBUG = True

# ============================================================
# KEYWORD MAPPING FINAL (value = target Deskripsi di master_akun.xlsx)
# ============================================================
# Pastikan nilai (value) tepat sama maksudnya seperti entri Deskripsi di master_akun.xlsx
KEYWORD_MAP = {
    # PENDAPATAN
    "sewa kos": "Pendapatan sewa kos bulanan",
    "pendapatan sewa bulanan": "Pendapatan sewa kos bulanan",
    "sewa kamar": "Pendapatan sewa kos bulanan",
    "pendapatan sewa kamar": "Pendapatan sewa kos bulanan",

    "katering": "Layanan katering bulanan",
    "catering": "Layanan katering bulanan",

    "laundry": "Pendapatan laundry penghuni",
    "cuci baju": "Pendapatan laundry penghuni",

    "parkir motor": "Pendapatan sewa parkir motor",
    "sewa area parkir": "Pendapatan sewa parkir motor",
    "parkir": "Pendapatan sewa parkir motor",

    "parkir mobil": "Pendapatan sewa parkir mobil",

    "denda": "Pendapatan denda keterlambatan bayar",
    "denda bayar": "Pendapatan denda keterlambatan bayar",
    "denda terlambat": "Pendapatan denda keterlambatan bayar",

    "sewa ruang": "Pendapatan sewa ruang usaha warung",
    "sewa ruang usaha": "Pendapatan sewa ruang usaha warung",
    "sewa ruang kecil": "Pendapatan sewa ruang usaha warung",
    "ruang usaha": "Pendapatan sewa ruang usaha warung",

    # PENGELUARAN
    "pemeliharaan": "Biaya pemeliharaan bangunan dan kamar kos",
    "perawatan": "Biaya pemeliharaan bangunan dan kamar kos",
    "maintenance": "Biaya pemeliharaan bangunan dan kamar kos",

    "dokter": "Biaya kunjungan dokter karena sakit",
    "kunjungan dokter": "Biaya kunjungan dokter karena sakit",

    "obat": "Pengeluaran / Pembelian obat",

    "listrik": "Biaya listrik bulanan",

    "air": "Tagihan / biaya air PAM Bulanan",
    "pam": "Tagihan / biaya air PAM Bulanan",

    "wifi": "Biaya bulanan layanan internet & Wi-Fi",
    "wi-fi": "Biaya bulanan layanan internet & Wi-Fi",
    "internet": "Biaya bulanan layanan internet & Wi-Fi",

    "renov": "Biaya renovasi kecil (cat, perbaikan pintu)",
    "renovasi": "Biaya renovasi kecil (cat, perbaikan pintu)",
    "cat": "Biaya renovasi kecil (cat, perbaikan pintu)",
    "ngecat": "Biaya renovasi kecil (cat, perbaikan pintu)",
    "perbaikan": "Biaya renovasi kecil (cat, perbaikan pintu)",
    "pintu": "Biaya renovasi kecil (cat, perbaikan pintu)",

    "kasur": "Pembelian perabotan kamar kos (kasur, kipas, meja)",
    "kipas": "Pembelian perabotan kamar kos (kasur, kipas, meja)",
    "meja": "Pembelian perabotan kamar kos (kasur, kipas, meja)",
    "perabot": "Pembelian perabotan kamar kos (kasur, kipas, meja)",

    "pbb": "Pajak properti / PBB",
    "pajak": "Pajak properti / PBB",

    # TARIF BARU - tarif sewa
    "penyesuaian sewa": "Penyesuaian / Perubahan Tarif atau Harga Sewa Kos",
    "perubahan tarif": "Penyesuaian / Perubahan Tarif atau Harga Sewa Kos",
    "perubahan harga sewa": "Penyesuaian / Perubahan Tarif atau Harga Sewa Kos",
    "penyesuaian sewa kamar kos": "Penyesuaian / Perubahan Tarif atau Harga Sewa Kos",

    # TARIF BARU - pembangunan
    "pembangunan kamar": "Penyesuaian / Perubahan Biaya Pembangunan Kamar Kos",
    "biaya pembangunan": "Penyesuaian / Perubahan Biaya Pembangunan Kamar Kos",
    "pembangunan kos": "Penyesuaian / Perubahan Biaya Pembangunan Kamar Kos",
    "harga pembuatan": "Penyesuaian / Perubahan Biaya Pembangunan Kamar Kos",
    "kenaikan harga pembuatan": "Penyesuaian / Perubahan Biaya Pembangunan Kamar Kos",
    "perubahan harga kamar kos": "Penyesuaian / Perubahan Biaya Pembangunan Kamar Kos"
}

# ============================================================
# Helpers: cleaning + ngram
# ============================================================
def clean_text(text: str) -> str:
    if not isinstance(text, str):
        return ""
    text = text.lower()
    text = re.sub(r'[^a-z0-9\s]', ' ', text)
    return re.sub(r'\s+', ' ', text).strip()

def ngram(tokens, n=3):
    return {tuple(tokens[i:i+n]) for i in range(len(tokens) - n + 1)}

def similarity_ngram(a: str, b: str, n=3) -> float:
    ta = clean_text(a).split()
    tb = clean_text(b).split()
    if len(ta) < n or len(tb) < n:
        sa, sb = set(ta), set(tb)
        if not sa or not sb:
            return 0.0
        return len(sa & sb) / len(sa | sb)
    na = ngram(ta, n)
    nb = ngram(tb, n)
    if not na or not nb:
        return 0.0
    return len(na & nb) / len(na | nb)

# ============================================================
# Build keyword -> master.desc_clean mapping (synchronize with master)
# ============================================================
def build_keyword_to_master_map(KEYWORD_MAP, df_master):
    """
    Returns dict: keyword -> desc_clean (string)
    Only keeps keywords whose target description exists in master.
    """
    mapping = {}
    # prepare master desc_clean -> original Deskripsi
    df_master["desc_clean"] = df_master["Deskripsi"].astype(str).apply(clean_text)
    available_desc_clean = set(df_master["desc_clean"].tolist())

    for key, target_descr in KEYWORD_MAP.items():
        target_clean = clean_text(str(target_descr))
        if target_clean in available_desc_clean:
            mapping[key] = target_clean
        else:
            # jika target tidak ada persis di master, tambahkan mapping ke closest master via exact token overlap
            # cari master dengan overlap terbesar
            best_idx = None
            best_overlap = 0
            target_tokens = set(target_clean.split())
            for idx, row in df_master.iterrows():
                mclean = row["desc_clean"]
                overlap = len(target_tokens & set(mclean.split()))
                if overlap > best_overlap:
                    best_overlap = overlap
                    best_idx = idx
            if best_idx is not None and best_overlap > 0:
                mapping[key] = df_master.at[best_idx, "desc_clean"]
            else:
                # biarkan keyword dihapus (tidak valid) — caller akan fallback ke n-gram
                # jika DEBUG aktif, tampilkan peringatan
                if DEBUG:
                    print(f"⚠ Warning: keyword target '{target_descr}' (key='{key}') tidak ditemukan di master dan tidak cocok; akan diabaikan.")
    return mapping

# ============================================================
# Keyword fallback uses desc_clean strings
# ============================================================
def keyword_fallback_using_desc_clean(desc: str, kw_to_master_map):
    d = clean_text(desc)
    kandidat = []
    for key, desc_clean in kw_to_master_map.items():
        if key in d:
            kandidat.append((key, desc_clean))
    if not kandidat:
        if DEBUG:
            print("   ⚠ Tidak ada keyword match")
        return None
    kandidat.sort(key=lambda x: len(x[0]), reverse=True)  # prefer longer (more specific) key
    key_used, desc_clean_used = kandidat[0]
    if DEBUG:
        print(f"   🔎 Keyword match → '{key_used}' → master_desc_clean='{desc_clean_used}'")
    return desc_clean_used

# ============================================================
# MAIN PROCESS (final)
# ============================================================
def process_ngram_matching(
    master_file="master_akun.xlsx",
    master_sheet="Data",
    trx_file="transaksi.xlsx",
    trx_sheet="Data",
    output_file="transaksi_dengan_kategori.xlsx",
    output_sheet="Data"
):
    # load master & transaksi
    df_master = pd.read_excel(master_file, sheet_name=master_sheet)
    df_trx = pd.read_excel(trx_file, sheet_name=trx_sheet)

    # normalize master descriptions
    df_master["Deskripsi"] = df_master["Deskripsi"].astype(str)
    df_master["desc_clean"] = df_master["Deskripsi"].apply(clean_text)

    # build keyword -> master desc_clean map
    kw2master = build_keyword_to_master_map(KEYWORD_MAP, df_master)
    if DEBUG:
        print(f"\nBuilt keyword->master map: {len(kw2master)} keywords active.\n")

    akun_list = []
    kategori_list = []
    nominal_list = []
    tarif_baru_list = []

    master_desc_list = df_master["Deskripsi"].tolist()
    master_desc_clean_list = df_master["desc_clean"].tolist()

    print("\n==================== MULAI DEBUG ====================\n") if DEBUG else None

    for idx, row in df_trx.iterrows():
        desc = str(row.get("Deskripsi Transaksi", ""))
        nominal_asli = row.get("Nominal", 0)

        if DEBUG:
            print(f"\n[{idx+1}] 📝 Deskripsi asli: {desc}")

        # try keyword -> returns desc_clean if matched
        matched_desc_clean = keyword_fallback_using_desc_clean(desc, kw2master)

        # if not found by keyword -> n-gram over master desc_clean (choose best match index)
        chosen_master_index = None
        if matched_desc_clean is None:
            if DEBUG:
                print("   🔄 Masuk mode n-gram similarity (backup)...")
            best_score = 0.0
            best_idx = None
            for i, mclean in enumerate(master_desc_clean_list):
                score = similarity_ngram(desc, mclean)
                if score > best_score:
                    best_score = score
                    best_idx = i
            if best_idx is not None:
                chosen_master_index = best_idx
                if DEBUG:
                    print(f"   🔎 N-gram memilih master row {best_idx} -> '{master_desc_list[best_idx]}' (score={best_score:.4f})")
        else:
            # find index of matched_desc_clean in master
            try:
                chosen_master_index = df_master.index[df_master["desc_clean"] == matched_desc_clean][0]
                if DEBUG:
                    print(f"   ✅ Ditemukan master index {chosen_master_index} via keyword.")
            except Exception:
                chosen_master_index = None

        # resolve akun (Deskripsi as in master) and kategori
        if chosen_master_index is None:
            akun = "Tidak Ditemukan"
            kategori = "Tidak Ditemukan"
            if DEBUG:
                print("   ❌ Tidak ada akun/kategori cocok di master (hasil fallback).")
        else:
            akun = df_master.at[chosen_master_index, "Deskripsi"]
            kategori = df_master.at[chosen_master_index, "Kategori"]
            if DEBUG:
                print(f"   📌 Matched akun (Deskripsi master): '{akun}'")
                print(f"   📌 Matched kategori: '{kategori}'")

        # apply nominal/tarif logic
        if kategori == "Pendapatan":
            nominal = abs(nominal_asli)
            tarif_baru = 0
        elif kategori == "Pengeluaran":
            nominal = -abs(nominal_asli)
            tarif_baru = 0
        elif kategori == "Tarif Baru":
            nominal = 0
            tarif_baru = abs(nominal_asli)
        else:
            nominal = nominal_asli
            tarif_baru = 0

        akun_list.append(akun)
        kategori_list.append(kategori)
        nominal_list.append(nominal)
        tarif_baru_list.append(tarif_baru)

    print("\n==================== DEBUG SELESAI ====================\n") if DEBUG else None

    # output
    df_out = df_trx.copy()
    df_out["Akun"] = akun_list
    df_out["Kategori"] = kategori_list
    df_out["Nominal"] = nominal_list
    df_out["Tarif Baru"] = tarif_baru_list

    # reorder columns if possible
    desired = ["Nomor", "Deskripsi Transaksi", "Akun", "Kategori", "Nominal", "Tarif Baru"]
    cols = [c for c in desired if c in df_out.columns]
    df_out = df_out[cols]

    df_out.to_excel(output_file, sheet_name=output_sheet, index=False)
    print("✔ File berhasil dibuat:", output_file)

# entry
if __name__ == "__main__":
    process_ngram_matching()

