# -*- coding: utf-8 -*-
"""find_categories.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CcVp4nIPpr3H9_hRm7jUvlFVPYYiEoNk
"""

import pandas as pd
import re
from openpyxl import Workbook


def clean_text(text: str) -> str:
    """Membersihkan teks agar lebih mudah dicocokkan."""
    if not isinstance(text, str):
        return ""
    text = text.lower()
    text = re.sub(r'[^a-z0-9\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text


def ngram(tokens, n=3):
    """Membuat n-gram dari list token."""
    return {tuple(tokens[i:i+n]) for i in range(len(tokens)-n+1)}


def similarity_ngram(a: str, b: str, n=3) -> float:
    """
    Menghitung similarity 0–1 dari dua kalimat berdasarkan n-gram overlap.
    Jika teks terlalu pendek, fallback ke token intersection ratio.
    """
    ta = clean_text(a).split()
    tb = clean_text(b).split()

    if len(ta) < n or len(tb) < n:
        # fallback similarity sederhana
        set_a, set_b = set(ta), set(tb)
        if not set_a or not set_b:
            return 0.0
        return len(set_a & set_b) / len(set_a | set_b)

    ng_a = ngram(ta, n)
    ng_b = ngram(tb, n)

    if not ng_a or not ng_b:
        return 0.0

    return len(ng_a & ng_b) / len(ng_a | ng_b)


def find_best_match(desc, master_desc_list):
    """Mengambil deskripsi master_akun dengan similarity terbesar."""
    best_score = 0
    best_item = None

    for master_desc in master_desc_list:
        score = similarity_ngram(desc, master_desc, n=3)
        if score > best_score:
            best_score = score
            best_item = master_desc

    return best_item, best_score


def process_ngram_matching(
    master_file="master_akun.xlsx",
    master_sheet="Data",
    trx_file="transaksi.xlsx",
    trx_sheet="Data",
    output_file="transaksi_dengan_kategori.xlsx",
    output_sheet="Data"
):
    """
    Proses utama: membaca master, transaksi, melakukan matching kategori,
    lalu menulis output Excel sesuai format contoh.
    """

    # === 1. Load data ===
    df_master = pd.read_excel(master_file, sheet_name=master_sheet)
    df_trx = pd.read_excel(trx_file, sheet_name=trx_sheet)

    # Pastikan kolom penting ada
    if "Deskripsi" not in df_master.columns or "Kategori" not in df_master.columns:
        raise ValueError("master_akun.xlsx harus memiliki kolom 'Deskripsi' dan 'Kategori'!")

    if "Deskripsi Transaksi" not in df_trx.columns or "Nominal" not in df_trx.columns:
        raise ValueError("transaksi.xlsx harus memiliki kolom 'Deskripsi Transaksi' dan 'Nominal'!")

    master_desc_list = df_master["Deskripsi"].astype(str).tolist()

    # === 2. Matching ===
    matched_categories = []
    adjusted_nominal = []
    tarif_baru_column = []

    for _, row in df_trx.iterrows():
        desc = row["Deskripsi Transaksi"]
        original_nominal = row["Nominal"]

        best_match, score = find_best_match(desc, master_desc_list)

        if best_match is None:
            kategori = "Tidak Ditemukan"
        else:
            kategori = df_master.loc[df_master["Deskripsi"] == best_match, "Kategori"].values[0]

        # === 3. Atur nilai nominal sesuai aturan ===
        if kategori == "Pendapatan":
            nominal_out = abs(original_nominal)
            tarif_baru = 0

        elif kategori == "Pengeluaran":
            nominal_out = -abs(original_nominal)
            tarif_baru = 0

        elif kategori == "Tarif Baru":
            nominal_out = 0
            tarif_baru = abs(original_nominal)

        else:
            # fallback jika tidak ditemukan
            nominal_out = original_nominal
            tarif_baru = 0

        matched_categories.append(kategori)
        adjusted_nominal.append(nominal_out)
        tarif_baru_column.append(tarif_baru)

    # === 4. Buat output ===
    df_output = df_trx.copy()
    df_output["Akun"] = matched_categories
    df_output["Nominal"] = adjusted_nominal
    df_output["Tarif Baru"] = tarif_baru_column

    # === 5. Tulis ke Excel ===
    with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
        df_output.to_excel(writer, sheet_name=output_sheet, index=False)


# Untuk kebutuhan import, jangan jalankan otomatis.
if __name__ == "__main__":
    process_ngram_matching()